### PR TITLE
Fixing pull --beta and refactoring along the way

### LINKED ISSUE #1083: pull --beta doesn't respect openfn.yaml
The beta pull doesn't take advantage of any of the nice new workspace stuff. So when you pull, it won't look in openfn.yaml for config - it'll just use defaults

In practice this means I can't easily pull state in json format

### PR DESCRIPTION
**Pull request by josephjclark**
Had to get an old state.json format for Elias and it turned into a nightmare

Basically `pull` was written before a lot of our nice `Workspace` APIs and stuff, and was rushed out even then

And what's happening is the pull isn't using config properly from the openfn.yaml file

This PR basically plugs in the Workspace class to make life easier.

But I hit loads of little problems on the way - the code here is super messy and we really need to tidy up a bit

Fixes #1083

## Headline changes

* Rename `project.repo` to `project.config`
* Generally renamed the repo/config stuff do "Workspace Config", or  variations of
* Centralised option parsing into a single file, which sets defaults
* Introduced a new project.yaml format  (`{ project, workspace }`)
* Standardised and simplified how we load openfn.yaml

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

### CODE REVIEW

File: packages/cli/src/pull/beta.ts [hunk 1]
```diff
@@ -37,47 +37,52 @@ export type PullOptionsBeta = Required<
...
 
+  // TODO `path` or `output` ?
+  // I don't think I want to model this as output. deploy is really
+  // designed to run from the working folder
+  // could be projectPath or repoPath too
+  const outputRoot = path.resolve(options.path || '.');
+
+  // TODO is outputRoot the right dir for this?
+  const workspace = new Workspace(outputRoot);
+  const config = workspace.getConfig();
```
Comment (josephjclark) [inline packages/cli/src/pull/beta.ts]: Not a fan of the getter - I just want to use workspace.config here. Why make it private?

File: packages/cli/src/pull/beta.ts [hunk 2]
```diff
@@ -37,47 +37,52 @@ export type PullOptionsBeta = Required<
...
-
   const projectFileName = project.getIdentifier();
 
   await fs.mkdir(`${outputRoot}/.projects`, { recursive: true });
   let stateOutputPath = `${outputRoot}/.projects/${projectFileName}`;
 
   const workflowsRoot = path.resolve(
     outputRoot,
-    project.repo?.workflowRoot ?? 'workflows'
+    project.repo.dirs?.workflows ?? 'workflows'
```
Comment (josephjclark) [inline packages/cli/src/pull/beta.ts]: Shouldn't need any of this optional chaining bullshit: I want good robust config with everything defaulted

**Comment by josephjclark** [comment]
Oh and `openfn.yaml` needs to look like this:
```
project:
workspace:
```

That gives you metadata about the checked out project, and config for the workspace generally

We should support legacy and new file formats for a while, but always serialize to the new

**Comment by josephjclark** [comment]
`openfn.yaml` now looks like this:
```
project:
  uuid: d3367267-ef25-41cf-91b2-43d18f831f3c
  endpoint: https://app.staging.openfn.org
  env: project
  inserted_at: 2025-10-21T17:10:57Z
  updated_at: 2025-10-21T17:10:57Z
workspace:
  dirs:
    projects: .projects
    workflows: workflows
  formats:
    openfn: yaml
    project: json
    workflow: json
```

Old yaml files, pre 0.6, are still 100% compatible. Very few tests have updated to the new structure.

:man_cook: :kiss:

**Comment by josephjclark** [comment]
@doc-han When you get a chance I'd like you to have a close look over this please: partly for your opinions (this is the right thing to do right??) but also to keep you in-sync with the changes. There's  more work I want to do and you might be "it" for the next ticket

**Comment by josephjclark** [comment]
@doc-han agreed - let's try and fix those as we go. We should be striving to improve the typing and general semantics on every PR from here going forward - I welcome your contributions in cleaning this all up!
