### PR TITLE
Fix error reporting issue

### LINKED ISSUE #317: CLI error: invalid workflow
An issue has cropped up where a failed dhis2 request is causing the whole workflow to abort with "invalid workflow".

It looks like this will happen whenever a job throws - which is odd because I'm sure I added a bunch of error handling for this.

This issue is to track an investigation into the problem.

### PR DESCRIPTION
**Pull request by josephjclark**
A issue crept up where a dangling unidentified variable was getting referenced in the error reporter causing a blow up.

It's been fixed, and I've improved the typing and tests.

This should really have been picked up by the build failing for type errors.

## Related issue

Fixes #317

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] If needed, I've updated the changelog
- [ ] Amber has QA'd this feature

### CODE REVIEW

File: packages/runtime/src/util/log-error.ts [hunk 1]
```diff
@@ -21,9 +22,8 @@ const createErrorReporter = (logger: Logger): ErrorReporter => {
       report.code = error.code as string;
       report.stack = error.stack as string;
     }
-
     logger.debug(`Error thrown by job ${jobId}`);
-    logger.error(`${error.code || error.name || type}: ${report.message}`);
+    logger.error(`${report.code || report.name || 'error'}: ${report.message}`);
```
Comment (josephjclark) [inline packages/runtime/src/util/log-error.ts:26]: This is the actual fix - the rest of the PR is typings and tests.
