### PR TITLE
Runtime: better errors

### LINKED ISSUE #720: Error objects don't log well
A few adaptors have a pattern where they create an Error object and throw it.

image

This isn't itself unreasonable!

But when serializing that error for the console or the final state, we lose all the detail.

If I console.log this error, I do see some of the properties:
image

Here you can see my custom `status` code. 

The stack trace right now is not useful - although will be once we handle source mapping

The thing we report in the CLI isn't so good:

image

And the thing we write to state is useless:

image

No surprises here, it's just getting a better understanding of how different errors are reported out of the runtime

### PR DESCRIPTION
**Pull request by josephjclark**
We've had ongoing problems getting errors out of the runtime, with too much information being obscured.

There's a few reasons for this  - the biggest one being that I've designed error handling around Error objects, but errors aren't actually serializable, with mixed results.

This PR basically serializes an error before a) logging it and b) writing it to state.

This ensures that the error is visible in the logs and on the resulting object.

What is nice as that as well as having more content, the updated tests have, IMO, cleaner error objects.

#726 is tracking a better, more holistic fix in this area. But this gets us out of hot water for now relatively cheaply.

## Issues

Closes #720 #612  https://github.com/OpenFn/adaptors/issues/624

## Screenshots

**401s coming out of odk:**

This is important because it shows the common http error object getting serialzied nicely (it also writes to state)

```
[CLI] ♦ Versions:
         ▸ node.js                 18.12.1
         ▸ cli                     1.4.2
         ▸ @openfn/language-odk    monorepo
[CLI] ✔ Loading adaptors from monorepo at /d/repo/openfn/adaptors
[CLI] ⚠ Skipping auto-install as monorepo is being used
[CLI] ✔ Compiled all expressions in workflow
WARNING: no authentication properties found on congfiguration schema!
    
Make sure to either set an access_token or email & password
[R/T] ✘ Failed step job-1 after 745ms
[R/T] ✘ [AdaptorError: GET to https://sandbox.getodk.cloud/v1/projects/66/forms returned 401: Unauthorized] {
  source: 'runtime',
  type: 'AdaptorError',
  severity: 'fail',
  details: Error: GET to https://sandbox.getodk.cloud/v1/projects/66/forms returned 401: Unauthorized
      at assertOK (/d/repo/openfn/adaptors/packages/common/dist/util.cjs:93:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async request (/d/repo/openfn/adaptors/packages/common/dist/util.cjs:158:3)
      at async /d/repo/openfn/adaptors/packages/odk/dist/index.cjs:157:22
      at async file:///d/repo/openfn/kit/packages/runtime/dist/index.js:581:20
      at async file:///d/repo/openfn/kit/packages/runtime/dist/index.js:545:20 {
    statusCode: 401,
    statusMessage: 'Unauthorized',
    url: 'https://sandbox.getodk.cloud/v1/projects/66/forms',
    duration: 595,
    method: 'GET',
    body: {
      message: 'Could not authenticate with the provided credentials.',
      code: 401.2
    },
    headers: {
      server: 'nginx',
      date: 'Tue, 02 Jul 2024 14:37:19 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '80',
      connection: 'keep-alive',
      etag: 'W/"50-ZRrLMzj8S67I1VD1Vnbql2PHY1Y"',
      'strict-transport-security': 'max-age=63072000'
    }
  }
}
[R/T] ✘ Check state.errors.job-1 for details.
[CLI] ✔ State written to tmp/errors/output.json
[CLI] ⚠ Errors reported in 1 jobs
[CLI] ✔ Finished in 860ms
```

**Reference errors**

image

### CODE REVIEW

File: packages/runtime/src/errors.ts [hunk 1]
```diff
@@ -69,20 +69,6 @@ export class RTError extends Error {
...
     Error.captureStackTrace(this, RTError.constructor);
-
-    // Provide custom rendering of the error in node
-    // TODO we should include some kind of context where it makes sense
-    // eg, if the error is associated with a job, show the job code
-    // eg, if the error came from an expression, show the source and location
-    // eg, if this came from our code, it doesn't help the user to see it but it does help us!
-    // @ts-ignore
-    this[util.inspect.custom] = (_depth, _options, _inspect) => {
-      const str = `[${this.name}] ${this.message}`;
```
Comment (josephjclark) [inline packages/runtime/src/errors.ts:80]: This turned out to be a major cause of information getting lost :(

**Comment by josephjclark** [comment]
TODO: a little worker testing locally, and running through a couple more cases in the issues. But I think this is about ready.
